import{a as I,S as M,i as s}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="48146281-74a8df349cdfa7f862384d5f8",$="https://pixabay.com/api/";async function y(t,r=1,i=15){try{return(await I.get($,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:i}})).data}catch(n){throw console.error("Error fetching images:",n),n}}function p(t){return t.map(({webformatURL:r,largeImageURL:i,tags:n,likes:e,views:o,comments:a,downloads:H})=>`
      <a href="${i}" class="gallery__item">
        <div class="image-card">
          <img src="${r}" alt="${n}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${o}</p>
            <p><b>Comments:</b> ${a}</p>
            <p><b>Downloads:</b> ${H}</p>
          </div>
        </div>
      </a>
    `).join("")}const B=document.querySelector("#search-form"),d=document.querySelector(".gallery"),b=document.querySelector("#loader"),h=document.querySelector("#load-more-btn");let g="",l=1,u=0,w=new M(".gallery a"),f=!1,c=!0;function L(){b.style.display="block"}function v(){b.style.display="none"}function O(){d.innerHTML=""}function P(){h.style.display="block"}function m(){h.style.display="none"}async function _(t){g=t,l=1,u=0,c=!0,O(),m(),L();try{const r=await y(t,l);u=r.totalHits,r.hits.length===0?s.error({title:"Error",message:"No images found!"}):(d.innerHTML=p(r.hits),w.refresh(),r.totalHits>15&&P())}catch{s.error({title:"Error",message:"Failed to fetch images."})}finally{v()}}async function E(){if(!(f||!c)){f=!0,l+=1,L();try{const t=await y(g,l);t.hits.length===0?(s.info({title:"Info",message:"You've reached the end of the results."}),c=!1,m()):(d.insertAdjacentHTML("beforeend",p(t.hits)),w.refresh(),l*15>=u&&(m(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),c=!1),x())}catch{s.error({title:"Error",message:"Failed to load more images."})}finally{f=!1,v()}}}B.addEventListener("submit",t=>{t.preventDefault();const r=t.target.elements.searchQuery.value.trim();r?_(r):s.warning({title:"Warning",message:"Search query cannot be empty!"})});h.addEventListener("click",()=>{window.removeEventListener("scroll",S),E()});window.addEventListener("scroll",S);function S(){window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-100&&g&&c&&E()}function x(){const t=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
